# Add / Update Password
---
- name: Set Password
  hosts: all

  tasks:
  - name: Set Password
    user:
      name: nick
      update_password: always
      password:  "{{'abcd123' | password_hash('sha512')}}"