# Conditions in Ansible
---
- name: Installing Httpd
  hosts: all

  tasks:
  - name: Install httpd on redhat
    yum:  
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install apache2 on Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Ubuntu"

# cmd - ansible localhost -m setup : to get the info about this remote server along with the build in variable